### ISSUE TITLE
最新版へ対応を希望

### ISSUE THREAD

**Issue by ev0tto** [noitaro/python-umamusume#1]
- たまにお知らせを閉じることができない。
- ガチャを最初に開くと有料10連のページに飛ぶため、ガチャを回す動作が正常に行われない。
-上記等の未対応の要素により、ストーリータブを開いたりとタイミングとクリック位置が合わなくなっている。

**Comment by ev0tto** [comment]
@DenimPauel氏のフォーク版にて前述のissueは解消。ありがとうございます。
日付更新時の処理と、アプリがフリーズした際の処理に改善の余地があるように感じました。

- 日付更新時の動作→画像認識を用いて対応
- ロード画面(Tipsが表示される)でフリーズ→Tipsの枠を認識させ、タスキルすることで暫定的に対応(不安定)
   別案として一定時間画面に動きがなかった場合、タスキルという方法も考えたが私の技術ではうまく動かず。


こちらのリポジトリを確認されてるかはわかりませんが、本家様にお時間に余裕のあるときにでも対応していただけたらと思います。

**Comment by noitaro** [comment]
Issues も Pull requests も気づいてなかったです。すみません。
せっかく @DenimPauel氏に対応して頂いたのに、気づかず私の方も対応しちゃいました。

これから @DenimPauel氏の対応をマージします。
わざわざご連絡ありがとうございます。

**Comment by noitaro** [comment]
@DenimPauel さんの対応をマージしました。
一通り動くの確認できましたが、変なところがあれば教えてください。

**Comment by ev0tto** [comment]
返信が遅くなってごめんなさい。
対応ありがとうございます！完璧に動作しました！

**Comment by noitaro** [comment]
@ev0tto さん
こちらも気づかなくてすみませんでした。
あと、改善点も上げてくださりありがとうございます。
またGitの使い方も勉強しながら、いろいろといじくっていきたいと思います！！
